
colors = {
  shieldColor = {1,182,240, 255},
  white = {255,255,255, 255},
  clear = {0, 0, 0, 0, 0},
  over = {0, 0, 0, 100},
  pressed = {0, 0, 0, 200},
  blue = {3,3,219, 255},
  green = {1,124,13, 255},
  goodBuildingPlacement = {1,124,13, 100},
  red = {200,0,0, 255},
  badBuildingPlacement = {200, 0, 0, 100},
  yellow = {239,169,0, 255},
  brown = {92, 56 ,0, 255},
  grey = {92, 92, 92, 255},
  black = {30,30,30, 255},
}

gui.mainMenuElements = {
	{ --menuBackground
		showing = true,
		fill = true,
		color = colors.blue,
		group = "menu",
		x = screenWidth/2 - 202, --centered
		y = screenHeight/2 - 295,
		width = 400,
		height = 500,
	},
	{
		text = "New Game",
		group = "menu",
		textColor = colors.blue,
		fill = true,
    showing = true,
		x = screenWidth/2 - 190,
		y = screenHeight/2 - 125,
		overColor = colors.grey,
		clickColor = colors.black,
		width  = 180,
		height = 30,
		onClicked = function() gui.loadGame() end,
		-- onClicked = "toggleGroup",
		-- parameter = "loadGame"
	},
	{
		text = "Load Game",
		group = "menu",
		textColor = colors.blue,
		fill = true,
    showing = true,
		x = screenWidth/2 - 190,
		y = screenHeight/2 - 90,
		overColor = colors.grey,
		clickColor = colors.black,
		width  = 180,
		height = 30,
		onClicked = function() gui.loadGame() end,
		-- onClicked = "toggleGroup",
		-- parameter = "loadGame"
	},
	{
		text = "Host Game",
		group = "menu",
		textColor = colors.blue,
		fill = true,
    showing = true,
		x = screenWidth/2 - 190,
		y = screenHeight/2 - 55,
		overColor = colors.grey,
		clickColor = colors.black,
		width  = 180,
		height = 30,
		onClicked = function() gui.loadGame() end,
		-- onClicked = "toggleGroup",
		-- parameter = "loadGame"
	},
	{
		text = "Join Game",
		group = "menu",
		textColor = colors.blue,
		fill = true,
    showing = true,
		x = screenWidth/2 - 190,
		y = screenHeight/2 - 20,
		overColor = colors.grey,
		clickColor = colors.black,
		width  = 180,
		height = 30,
		onClicked = function() gui.loadGame() end,
		-- onClicked = "toggleGroup",
		-- parameter = "loadGame"
	},
  { --test text input
		group = "menu",
    textBox = true,
		textColor = colors.white,
		fill = false,
    outline = true,
    showing = true,
		x = screenWidth/2 - 190,
		y = screenHeight/2 + 15,
		overColor = colors.grey,
		clickColor = colors.black,
		width  = 180,
		height = 30,
		onFinished = function(text)
      if (love.filesystem.exists("src/scenarios/"..text..".lua")) then
        scene = game:new("src/scenarios/"..text)
      end
    end
		-- onClicked = "toggleGroup",
		-- parameter = "loadGame"
	},
  {
		text = "Exit to Desktop",
    group = "menu",
		textColor = colors.blue,
		fill = true,
    showing = true,
		x = screenWidth - 190,
		y = screenHeight - 245,
		overColor = colors.grey,
		clickColor = colors.black,
		width  = 180,
		height = 30,
		onClicked = function() love.event.quit() end,
	}
}

local screenHeight = screenHeight
local screenWidth = screenWidth
local universalShortcuts = {
["f10"] = "menu",
-- [" "] = deselect,
["b"] = "build"
}
local selectedShortcuts = {
-- ["a"] = attackMove,
-- ["m"] = move,
}
local buildBar = false

gui.gameElements = {
	--MENU
	{ --menu button
		shortcut = "f10",
		text = "menu",
		textColor = colors.blue,
		fill = true,
		showing = true,
		x = screenWidth -62,
		y = screenHeight - 45,
		overColor = colors.grey,
		clickColor = colors.black,
		width  = 60,
		height = 25,
		onClicked = function() gui.toggleGroup("menu") end,
	},{ --menuBackground
		fill = true,
		color = colors.blue,
		group = "menu",
		x = screenWidth - 202, --centered
		y = screenHeight - 295,
		width = 200,
		height = 250,
	},{ --close menu button
		text = "Close",
		group = "menu",
		textColor = colors.blue,
		fill = true,
		x = screenWidth - 190,
		y = screenHeight - 85,
		overColor = colors.grey,
		clickColor = colors.black,
		width  = 180,
		height = 30,
		onClicked = function() gui.toggleGroup("menu") end,
	},{
		text = "Load Game",
		group = "menu",
		textColor = colors.blue,
		fill = true,
		x = screenWidth - 190,
		y = screenHeight - 125,
		overColor = colors.grey,
		clickColor = colors.black,
		width  = 180,
		height = 30,
		onClicked = function() gui.loadGame() end,
		-- onClicked = "toggleGroup",
		-- parameter = "loadGame"
	},{
		text = "Save Game",
		group = "menu",
		textColor = colors.blue,
		fill = true,
		x = screenWidth - 190,
		y = screenHeight - 165,
		overColor = colors.grey,
		clickColor = colors.black,
		width  = 180,
		height = 30,
		onClicked = function() gui.saveGame() end,
		-- onClicked = "toggleGroup",
		-- parameter = "saveGame"
	},{
		text = "Options",
		group = "menu",
		textColor = colors.blue,
		fill = true,
		x = screenWidth - 190,
		y = screenHeight - 205,
		overColor = colors.grey,
		clickColor = colors.black,
		width  = 180,
		height = 30,
		onClicked = function() gui.toggleGroup("options") end,
	},{
		text = "Exit to Desktop",
		group = "menu",
		textColor = colors.blue,
		fill = true,
		x = screenWidth - 190,
		y = screenHeight - 245,
		overColor = colors.grey,
		clickColor = colors.black,
		width  = 180,
		height = 30,
		onClicked = function() love.event.quit() end,
	},{
		text = "Main Menu",
		group = "menu",
		textColor = colors.blue,
		fill = true,
		x = screenWidth - 190,
		y = screenHeight - 285,
		overColor = colors.grey,
		clickColor = colors.black,
		width  = 180,
		height = 30,
		onClicked = function() gui.toggleGroup("menu") scene = mainMenu:new() end,
	},

	--OPTIONS
	{ --options background
		fill = true,
		color = colors.blue,
		group = "options",
		x = screenWidth/2 - 200, --centered
		y = screenHeight/2 - 200,
		width = 400,
		height = 400,
	},
	-- { --screen resolution
	-- 	group = "options",
	-- 	--textColor = colors.blue,
	-- 	x = screenWidth/2,
	-- 	y = screenHeight/2,
	-- 	spacing = 60,
	-- 	width = 200,
	-- 	list = {
	-- 		"920x720",
	-- 		"1024x920",
	-- 		"1366x768",
	-- 		"1920x1080"
	-- 	},
	-- },
	{ --fullscreen
		text = "Toggle Fullscreen",
		group = "options",
		textColor = colors.blue,
		fill = true,
		x = screenWidth/2 - 190,
		y = screenHeight/2 - 180,
		overColor = colors.grey,
		clickColor = colors.black,
		width  = 200,
		height = 30,
		onClicked = function() love.window.setFullscreen( not love.window.getFullscreen()) end,
	},
	{ --antialiasing
		text = "Toggle AA",
		group = "options",
		textColor = colors.blue,
		fill = true,
		x = screenWidth/2 - 190,
		y = screenHeight/2 - 145,
		overColor = colors.grey,
		clickColor = colors.black,
		width  = 120,
		height = 30,
		onClicked = function() local width, height, flags = love.window.getMode() flags.msaa = flags.msaa + 1 love.window.setMode(width,height, flags) end,
	},	{ --vsync
			text = "vsync",
			group = "options",
			textColor = colors.blue,
			fill = true,
			x = screenWidth/2 - 190,
			y = screenHeight/2 - 105,
			overColor = colors.grey,
			clickColor = colors.black,
			width  = 120,
			height = 30,
			onClicked = function() local width, height, flags = love.window.getMode() flags.vsync = not flags.vsync love.window.setMode(width,height, flags) end,
		},



	-- BUILD BAR
	{
		name = "oreMine",
		image = love.graphics.newImage("images/units/unitPics/resourceBuilding.png"),
		imageColor = colors.blue,
		y = screenHeight - 55,
		x = screenWidth - 300,
		width = 50,
		height = 50,
		onClicked = function() gui.buildUnit(oreMine) end,
		color = colors.clear,
		overColor = colors.over,
		clickColor = colors.pressed,
		fill = true,
		group = "buildBar",
		showing = true,
	},{
		name = "miningTruckFactory",
		image = love.graphics.newImage("images/units/unitPics/miningTruckFactoryIcon.png"),
		imageColor = colors.blue,
		y = screenHeight - 55,
		x = screenWidth - 355,
		width = 50,
		height = 50,
		onClicked = function() gui.buildUnit(miningTruckFactory) end,
		color = colors.clear,
		overColor = colors.over,
		clickColor = colors.pressed,
		fill = true,
		group = "buildBar",
		showing = true,
	},
	-- CargoSwitching
	{
		name = "cargo",
		shortcut = "",
		text = "cargo",
		textColor = colors.blue,
		fill = true,
		showing = true,
		x = 10,
		y = screenHeight - 45,
		overColor = colors.grey,
		clickColor = colors.black,
		width  = 60,
		height = 25,
		onClicked = function() gui.toggleGroup("cargo") end,
	},{
		name = "metalCargo",
		group = "cargo",
		image = love.graphics.newImage("images/gui/metalIcon.png"),
		imageColor = colors.gray,
		y = screenHeight - 75,
		x = 10,
		color = colors.clear,
		overColor = colors.over,
		clickColor = colors.pressed,
		fill = true,
		width = 60,
		height = 30,
		onClicked = function() gui.setSelectionCargo("metal") end,
	},{
		name = "oreCargo",
		group = "cargo",
		image = love.graphics.newImage("images/gui/oreIcon.png"),
		imageColor = colors.brown,
		y = screenHeight - 110,
		x = 10,
		color = colors.clear,
		overColor = colors.over,
		clickColor = colors.pressed,
		fill = true,
		width = 60,
		height = 30,
		onClicked = function() gui.setSelectionCargo("ore") end,
	},

}
